### ISSUE TITLE
checkbox option for selecting proteins in dot plot view

### ISSUE THREAD

**Issue by StKarMa** [knightjdr/prohits-viz-client#1]
to allow selecting preys directly form the dot plot might be useful sometimes

**Comment by knightjdr** [comment]
I'll likely add this via select-click on a row or column name. Single or double clicking is used by the chrome extension, so shift click would be a suitable alternative.

**Comment by knightjdr** [comment]
This can be done now by either right clicking and selecting from the context menu or alt-clicking on the name.
