### ISSUE TITLE
Dotplot: resorting function [prohits-viz.org]

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/prohits-viz-client#1]
Under generating customized image of dotplot using 'Gene Selection' tool:

Issue: Moving specific genes in the prey list from 'Selected' to 'Rows' will override previously reordered list back to the originally clustered list.

ie. I sorted preys manually in the 'selected' window. I find a prey that I would like to remove. When I move this prey to the 'Rows' panel, my manually sorted order is re-set back to the originally displayed clustered list.

**Comment by knightjdr** [comment]
Fixed.
