### ISSUE TITLE
Sorting by reference bait

### ISSUE THREAD

**Issue by gghesketh** [knightjdr/prohits-viz-client#10]
I really like the new sorting by reference bait feature. 

As it is currently though, the infinitely enriched or depleted pairs are sorted to the top. This is of course strictly accurate, but this forces you to scroll down (potentially) several pages to where the ratios actually become meaningful / interesting, and even then "meaningless" ratios will still be mixed in. Given that the main point of selecting a reference bait is that you want to see how other baits change relative to the reference, displaying all the preys at the top that weren't detected (or didn't pass the primary filter) is kind of distracting. Perhaps it would make sense (if possible) to be able to select some sort of criteria about the reference bait that must be met in order for the prey to be displayed.

For example, when you select the reference bait (or the bait to be sorted relative to the reference) could you have the ability to 1) select only show preys that pass primary filter, and / or 2) set abundance minimum for preys to be included in the sorted list.

I wonder if moving the reference / relative sorting option to the menu on the right would be easier. You could leave the "sort ascending / descending" options where they are by right clicking on the bait on the image, but then have a more advanced sorting tool in the menu. Perhaps you could select reference bait plus some simple filtering criteria (FDR cutoff, abundance minimum) then select the secondary bait and sorting / filtering criteria (ascending/descending, FDR cutoff, abundance minimum). Would also be nice to be able to set a fold change cutoff for the secondary bait - e.g., only display things with a >2 fold change.

This is effectively what I've been doing manually in Excel (using the "data_matrix" output from the viz 1.0 dotplot tool) to generate what have been extremely valuable lists. First I sort based on reference bait and then chop below a certain abundance minimum, and then do a second sort based on a second bait (which for me is usually the reference bait with particular prey knocked-out by CRISPR).

**Comment by knightjdr** [comment]
These features are online.
