### ISSUE TITLE
task status and viewing

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/prohits-viz-client#13]
After performing analysis to obtain dotplot visualization of the SAINT analysis, users are prompted to click on the link to results. Then we choose either 'log' or 'dotplot' from the scroll down options.

Compared to the older version, I find this a bit cumbersome to have to choose which file I'd like to open rather than being directed straight to the dotplot view. 

Alternatively, if this transition is to accommodate other functions to be implemented, it'd be best to show the options in the order that would be most frequently used. For instance, 'Dotplot' first and leave 'log' as the last option.

Cheers,
jiyoung

**Comment by knightjdr** [comment]
This has been updated to work similar to the old site, while keeping the new task view as well.
