### ISSUE TITLE
Dotplot generation from SAINT files/ [error: Missing header column] or [error: several prey names appear in Bait of dotplot]

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/prohits-viz-client#21]
I have six SAINTexpress files that I would like to use to generate a single dotplot. I obtained different errors when using prohits-viz.org versus prohits-viz.lunenfeld.ca.

I received SAINT files from a member of the lab, and believe they have not be altered. 
When using prohits-viz.org to generate a dotplot, I first received 'no parsed results', so I've removed the extra heading (boosted_by) by importing the txt files in Excel and removing this column, then saving it as a text files again.

However, I still see errors in
1. prohits-viz.org: 'missing header column'

2. prohits-viz.lunenfeld.ca: Dotplot is generated, however, several prey genes are represented in the bait axis.

I include two of six files here to see if you can identify the source of the problem:
[4092_DEDDA_MSGF.txt](https://github.com/knightjdr/prohits-viz-client/files/3039273/4092_DEDDA_MSGF.txt)

[4042_DEDDA_MC.txt](https://github.com/knightjdr/prohits-viz-client/files/3039270/4042_DEDDA_MC.txt)

Thanks,
Jiyoung

**Comment by knightjdr** [comment]
Fixed.
