### ISSUE TITLE
SAINT file input error

### ISSUE THREAD

**Issue by jiyoungyoun** [knightjdr/prohits-viz-client#23]
I manually combined two separate SAINT files into one using Microsoft Excel after importing the two files independently. 
This combined txt file can be used for https://prohits-viz.lunenfeld.ca, but I receive 'parsing error' in https://prohits-viz.org. 
It would be good to know what caused the parsing problem when using Excel to combine multiple SAINT files manually.
[G3BP1s_combined_3957_3959_4420_v2.txt](https://github.com/knightjdr/prohits-viz-client/files/3637041/G3BP1s_combined_3957_3959_4420_v2.txt)

**Comment by knightjdr** [comment]
It's an issue with how Excel saves a file on Mac. If you open one file and save it without making any changes, you'll get the same error.

I hadn't realized this would be an issue so thanks for letting me know.

If you want to combine two files at prohits-viz.org, you can just select both of them from the "select file" button. Hold the command key (Mac) or control key (Windows) when selecting files to grab multiple ones. Or you can drag and drop them onto the button

**Comment by knightjdr** [comment]
This is covered by issue #20, so I'm going to close this.
