### ISSUE TITLE
Making / sizing the "selection box"

### ISSUE THREAD

**Issue by gghesketh** [knightjdr/prohits-viz-client#4]
When you are dragging / sizing the selection box in the full image, if your mouse "bumps" the edge of the image the selection box locks.

**Comment by knightjdr** [comment]
The box doesn't lock it assumes that when you exit the image it is the same thing as releasing the mouse, i.e. you are making a selection.

This is the intended behaviour although I realize it is annoying. I'll try to figure out a solution.

**Comment by knightjdr** [comment]
This is fixed.

ebdcc2c2334155643d6bd910c023013682ca47bf
