### ISSUE TITLE
Gene search in custom image

### ISSUE THREAD

**Issue by gghesketh** [knightjdr/prohits-viz-client#7]
When using the gene search in the custom image, it doesn't reposition the image to show the searched gene (as it does in the full image view).

**Comment by knightjdr** [comment]
My assumption was people wouldn't have customized images much larger than the screen or would know what they had selected, but this is probably a bad assumption.

**Comment by knightjdr** [comment]
Fixed 79a88ceeeae5e4cc56647fa674c461e0eff024f5

Will update site next week.
