### ISSUE TITLE
Selecting abundance minimum

### ISSUE THREAD

**Issue by gghesketh** [knightjdr/prohits-viz-client#7]
When you change the "abundance minimum" within an already opened image, it simply removes the dot colour for those preys but leaves the preys visible. Is this what was intended? It seems to me that having those preys disappear from the plot makes more sense. (This is how it works in viz 1.0).

Another possibility would be to have an option with the "customize image" tool to select the minimum abundance you would like to display in the custom image.

**Comment by knightjdr** [comment]
Fixed.
